#ifndef GUISETTINGS
#define GUISETTINGS

#define GAME_QML_PLAGIN "ColonyControl"
#define MAX_NUMBER_OF_UNITS 400
#define MAX_NUMBER_OF_ABILITY_BUTTONS 40
#define DEFAULT_MOUSE_MARKER "/img/Marker.png"

#define ABILITY_BUTTON_SIZE 50

enum ABILITY_TYPE
{
	INVALIDE_TYPE = - 1,
	UPDATE_BUILDING,
	BUILDING_OBJECT,
	ABILITY
};

#endif // GUISETTINGS

