#ifndef HUMANUNITPROCESSING
#define HUMANUNITPROCESSING
#include "Enums/objects.h"

enum UNIT_STATUS
{
	NO_UNIT_STATUS = INVALIDE_VALUE,
	OPERATION = 0,
	ON_BASE,
	NUMBER_OF_UNIT_STATUS
};

enum SPECIAL_UNIT_STATUS
{
	NO_SPEC_STATUS = 0,
	FIND_RESOURCES,
	SUPPLY_RESOURCES,
	RETURN_TO_BASE,
	NUMBER_OF_SPEC_STATUS
};

#endif // HUMANUNITPROCESSING

