#include "humanplayer.h"
#include "Enums/procsettings/humanprocessingsettings.h"
#include "Core/UnitController/unitcontroller.h"
#include "Core/objectcontroller.h"
#include "humanbuildmanager.h"
#include "humanabilitymanager.h"


// ResPrototypeStotage for all AROI buildings
static ResPrototypeStotage s_humanResourses[] =
{
	// HUMAN_SETTLERS
	// BUILDING TYPE		lvl		 RES TYPE	   VALUE(N.S)		MAX VALUE		  HARD LIM		SIZE OF GROUP		PRODECED BY		GROUP PROD.	  COMPL.	 PROGRESS(N.S)	   MATERIAL	   MAT. COST	NATURAL	    REQUARED	 CONSUME   HARD REQ.   IMPORT	IMP. LIMIT	   EXPORT	EXP. LIMIT	   DISPLAY
	{	t_HUMAN_SETTLERS,	0,		{POPULATION,	NOT_SET,	HUM_SETTL_POP_LIM_0,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_SETTLERS,	1,		{POPULATION,	NOT_SET,	HUM_SETTL_POP_LIM_1,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_SETTLERS,	2,		{POPULATION,	NOT_SET,	HUM_SETTL_POP_LIM_2,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_SETTLERS,	3,		{POPULATION,	NOT_SET,	HUM_SETTL_POP_LIM_3,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_SETTLERS,	4,		{POPULATION,	NOT_SET,	HUM_SETTL_POP_LIM_4,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_SETTLERS,	5,		{POPULATION,	NOT_SET,	HUM_SETTL_POP_LIM_5,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_SETTLERS,	6,		{POPULATION,	NOT_SET,	HUM_SETTL_POP_LIM_6,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_SETTLERS,	7,		{POPULATION,	NOT_SET,	HUM_SETTL_POP_LIM_7,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_SETTLERS,	8,		{POPULATION,	NOT_SET,	HUM_SETTL_POP_LIM_8,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_SETTLERS,	9,		{POPULATION,	NOT_SET,	HUM_SETTL_POP_LIM_9,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_SETTLERS,	10,		{POPULATION,	NOT_SET,	HUM_SETTL_POP_LIM_10,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},

	// BUILDING TYPE		lvl		 RES TYPE	   VALUE(N.S)		MAX VALUE		  HARD LIM		SIZE OF GROUP		PRODECED BY		GROUP PROD.	  COMPL.	 PROGRESS(N.S)	   MATERIAL	   MAT. COST	NATURAL	    REQUARED	 CONSUME   HARD REQ.   IMPORT	IMP. LIMIT	   EXPORT	EXP. LIMIT	   DISPLAY
	{	t_HUMAN_SETTLERS,	0,		{SUPPLY,		NOT_SET,	HUM_SETTL_SUP_LIM_0,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	1,		{SUPPLY,		NOT_SET,	HUM_SETTL_SUP_LIM_1,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	2,		{SUPPLY,		NOT_SET,	HUM_SETTL_SUP_LIM_2,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	3,		{SUPPLY,		NOT_SET,	HUM_SETTL_SUP_LIM_3,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	4,		{SUPPLY,		NOT_SET,	HUM_SETTL_SUP_LIM_4,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	5,		{SUPPLY,		NOT_SET,	HUM_SETTL_SUP_LIM_5,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	6,		{SUPPLY,		NOT_SET,	HUM_SETTL_SUP_LIM_6,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	7,		{SUPPLY,		NOT_SET,	HUM_SETTL_SUP_LIM_7,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	8,		{SUPPLY,		NOT_SET,	HUM_SETTL_SUP_LIM_8,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	9,		{SUPPLY,		NOT_SET,	HUM_SETTL_SUP_LIM_9,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	10,		{SUPPLY,		NOT_SET,	HUM_SETTL_SUP_LIM_10,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},

	// BUILDING TYPE		lvl		 RES TYPE	   VALUE(N.S)		MAX VALUE		  HARD LIM		SIZE OF GROUP		PRODECED BY		GROUP PROD.	  COMPL.	 PROGRESS(N.S)	   MATERIAL	   MAT. COST	NATURAL	    REQUARED	 CONSUME   HARD REQ.   IMPORT	IMP. LIMIT	   EXPORT	EXP. LIMIT	   DISPLAY
	{	t_HUMAN_SETTLERS,	0,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_0,	 true,		GROUP_FROM_8,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	1,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_1,	 true,		GROUP_FROM_8,		POPULATION,			1,			2,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	2,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_2,	 true,		GROUP_FROM_8,		POPULATION,			1,			4,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	3,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_3,	 true,		GROUP_FROM_8,		POPULATION,			1,			8,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	4,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_4,	 true,		GROUP_FROM_8,		POPULATION,			1,			16,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	5,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_5,	 true,		GROUP_FROM_8,		POPULATION,			1,			32,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	6,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_6,	 true,		GROUP_FROM_8,		POPULATION,			1,			64,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	7,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_7,	 true,		GROUP_FROM_8,		POPULATION,			1,			128,		NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	8,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_8,	 true,		GROUP_FROM_8,		POPULATION,			1,			256,		NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	9,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_9,	 true,		GROUP_FROM_8,		POPULATION,			1,			512,		NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	10,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_10,	 true,		GROUP_FROM_8,		POPULATION,			1,			1024,		NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_SETTLERS,	11,		{INFROSTRUCTURE,NOT_SET,	HUM_SETTL_INF_LVL_10_max,true,		GROUP_FROM_8,		POPULATION,			1,			1024,		NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},


	// HUMAN_COLONY_CENTER
	// BUILDING TYPE			lvl		 RES TYPE	   VALUE(N.S)		MAX VALUE		  HARD LIM		SIZE OF GROUP		PRODECED BY		GROUP PROD.	  COMPL.	 PROGRESS(N.S)	   MATERIAL	   MAT. COST	NATURAL	    REQUARED	 CONSUME   HARD REQ.   IMPORT	IMP. LIMIT	   EXPORT	EXP. LIMIT	   DISPLAY
	{	t_HUMAN_COLONY_CENTER,	0,		{POPULATION,	NOT_SET,	HUM_COL_CENT_POP_LIM_0,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_COLONY_CENTER,	1,		{POPULATION,	NOT_SET,	HUM_COL_CENT_POP_LIM_1,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_COLONY_CENTER,	2,		{POPULATION,	NOT_SET,	HUM_COL_CENT_POP_LIM_2,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_COLONY_CENTER,	3,		{POPULATION,	NOT_SET,	HUM_COL_CENT_POP_LIM_3,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_COLONY_CENTER,	4,		{POPULATION,	NOT_SET,	HUM_COL_CENT_POP_LIM_4,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},

	// BUILDING TYPE			lvl		 RES TYPE	   VALUE(N.S)		MAX VALUE		  HARD LIM		SIZE OF GROUP		PRODECED BY		GROUP PROD.	  COMPL.	 PROGRESS(N.S)	   MATERIAL	   MAT. COST	NATURAL	    REQUARED	 CONSUME   HARD REQ.   IMPORT	IMP. LIMIT	   EXPORT	EXP. LIMIT	   DISPLAY
	{	t_HUMAN_COLONY_CENTER,	0,		{SUPPLY,		NOT_SET,	HUM_COL_CENT_SUP_LIM_0,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	1,		{SUPPLY,		NOT_SET,	HUM_COL_CENT_SUP_LIM_1,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	2,		{SUPPLY,		NOT_SET,	HUM_COL_CENT_SUP_LIM_2,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	3,		{SUPPLY,		NOT_SET,	HUM_COL_CENT_SUP_LIM_3,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	4,		{SUPPLY,		NOT_SET,	HUM_COL_CENT_SUP_LIM_4,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},

	// BUILDING TYPE			lvl		 RES TYPE	   VALUE(N.S)		MAX VALUE			HARD LIM	SIZE OF GROUP		PRODECED BY		GROUP PROD.	  COMPL.	 PROGRESS(N.S)	   MATERIAL	   MAT. COST	NATURAL	    REQUARED	 CONSUME   HARD REQ.   IMPORT	IMP. LIMIT	   EXPORT	EXP. LIMIT	   DISPLAY
	{	t_HUMAN_COLONY_CENTER,	0,		{INFROSTRUCTURE,NOT_SET,	HUM_COL_CENT_INF_LVL_0,	 true,		GROUP_FROM_8,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	1,		{INFROSTRUCTURE,NOT_SET,	HUM_COL_CENT_INF_LVL_1,	 true,		GROUP_FROM_8,		POPULATION,			1,			2,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	2,		{INFROSTRUCTURE,NOT_SET,	HUM_COL_CENT_INF_LVL_2,	 true,		GROUP_FROM_8,		POPULATION,			1,			4,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	3,		{INFROSTRUCTURE,NOT_SET,	HUM_COL_CENT_INF_LVL_3,	 true,		GROUP_FROM_8,		POPULATION,			1,			8,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	4,		{INFROSTRUCTURE,NOT_SET,	HUM_COL_CENT_INF_LVL_4,	 true,		GROUP_FROM_8,		POPULATION,			1,			16,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	5,		{INFROSTRUCTURE,NOT_SET,	HUM_COL_CENT_INF_LVL_4_max, true,	GROUP_FROM_8,		POPULATION,			1,			32,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
\
	// BUILDING TYPE			lvl		 RES TYPE	   VALUE(N.S)		MAX VALUE				HARD LIM	SIZE OF GROUP		PRODECED BY		GROUP PROD.	  COMPL.	 PROGRESS(N.S)	   MATERIAL	   MAT. COST	NATURAL	    REQUARED	 CONSUME   HARD REQ.   IMPORT	IMP. LIMIT	   EXPORT	EXP. LIMIT	   DISPLAY
	{	t_HUMAN_COLONY_CENTER,	0,		{SHIPS,			NOT_SET,	HUM_COL_CENT_SHIPS_LIM_0,	true,		GROUP_FROM_4,		POPULATION,			1,		  1400,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	1,		{SHIPS,			NOT_SET,	HUM_COL_CENT_SHIPS_LIM_1,	true,		GROUP_FROM_4,		POPULATION,			1,		  1400,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	2,		{SHIPS,			NOT_SET,	HUM_COL_CENT_SHIPS_LIM_2,	true,		GROUP_FROM_4,		POPULATION,			1,		  1400,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	3,		{SHIPS,			NOT_SET,	HUM_COL_CENT_SHIPS_LIM_3,	true,		GROUP_FROM_4,		POPULATION,			1,		  1400,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_COLONY_CENTER,	4,		{SHIPS,			NOT_SET,	HUM_COL_CENT_SHIPS_LIM_4,	true,		GROUP_FROM_4,		POPULATION,			1,		  1400,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},


	// HUMAN_TRANSPORT_CENTER
	// BUILDING TYPE				lvl		 RES TYPE	   VALUE(N.S)		MAX VALUE			  HARD LIM		SIZE OF GROUP		PRODECED BY		GROUP PROD.	  COMPL.	 PROGRESS(N.S)	   MATERIAL	   MAT. COST	NATURAL	    REQUARED	 CONSUME   HARD REQ.   IMPORT	IMP. LIMIT	   EXPORT	EXP. LIMIT	   DISPLAY
	{	t_HUMAN_TRANSPORT_CENTER,	0,		{POPULATION,	NOT_SET,	HUM_TRANS_CENT_POP_LIM_0,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_TRANSPORT_CENTER,	1,		{POPULATION,	NOT_SET,	HUM_TRANS_CENT_POP_LIM_1,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_TRANSPORT_CENTER,	2,		{POPULATION,	NOT_SET,	HUM_TRANS_CENT_POP_LIM_2,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},
	{	t_HUMAN_TRANSPORT_CENTER,	3,		{POPULATION,	NOT_SET,	HUM_TRANS_CENT_POP_LIM_3,	false,		GROUP_FROM_16,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	SUPPLY,			1,		true,		true,	PERCENT_25,		true,	PERCENT_12a5,	true}},

	// BUILDING TYPE				lvl		 RES TYPE	   VALUE(N.S)		MAX VALUE			  HARD LIM		SIZE OF GROUP		PRODECED BY		GROUP PROD.	  COMPL.	 PROGRESS(N.S)	   MATERIAL	   MAT. COST	NATURAL	    REQUARED	 CONSUME   HARD REQ.   IMPORT	IMP. LIMIT	   EXPORT	EXP. LIMIT	   DISPLAY
	{	t_HUMAN_TRANSPORT_CENTER,	0,		{SUPPLY,		NOT_SET,	HUM_TRANS_CENT_SUP_LIM_0,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_TRANSPORT_CENTER,	1,		{SUPPLY,		NOT_SET,	HUM_TRANS_CENT_SUP_LIM_1,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_TRANSPORT_CENTER,	2,		{SUPPLY,		NOT_SET,	HUM_TRANS_CENT_SUP_LIM_2,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_TRANSPORT_CENTER,	3,		{SUPPLY,		NOT_SET,	HUM_TRANS_CENT_SUP_LIM_3,	false,		GROUP_FROM_4,		POPULATION,			19,			1,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},

	// BUILDING TYPE				lvl		 RES TYPE	   VALUE(N.S)		MAX VALUE		  HARD LIM		SIZE OF GROUP		PRODECED BY		GROUP PROD.	  COMPL.	 PROGRESS(N.S)	   MATERIAL	   MAT. COST	NATURAL	    REQUARED	 CONSUME   HARD REQ.   IMPORT	IMP. LIMIT	   EXPORT	EXP. LIMIT	   DISPLAY
	{	t_HUMAN_TRANSPORT_CENTER,	0,		{INFROSTRUCTURE,NOT_SET,	HUM_TRANS_CENT_INF_LVL_0,	 true,		GROUP_FROM_8,		POPULATION,			1,			1,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_TRANSPORT_CENTER,	1,		{INFROSTRUCTURE,NOT_SET,	HUM_TRANS_CENT_INF_LVL_1,	 true,		GROUP_FROM_8,		POPULATION,			1,			2,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_TRANSPORT_CENTER,	2,		{INFROSTRUCTURE,NOT_SET,	HUM_TRANS_CENT_INF_LVL_2,	 true,		GROUP_FROM_8,		POPULATION,			1,			4,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_TRANSPORT_CENTER,	3,		{INFROSTRUCTURE,NOT_SET,	HUM_TRANS_CENT_INF_LVL_3,	 true,		GROUP_FROM_8,		POPULATION,			1,			8,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},
	{	t_HUMAN_TRANSPORT_CENTER,	4,		{INFROSTRUCTURE,NOT_SET,	HUM_TRANS_CENT_INF_LVL_3_max,true,		GROUP_FROM_8,		POPULATION,			1,			16,			NOT_SET,		NO_RES,		NOT_SET,	NOT_SET,	NO_RES,		 NOT_SET,	NOT_SET,	false,	NOT_SET,		false,	NOT_SET,		true}},

	// BUILDING TYPE				lvl		 RES TYPE	   VALUE(N.S)		MAX VALUE				HARD LIM	SIZE OF GROUP		PRODECED BY		GROUP PROD.	  COMPL.	 PROGRESS(N.S)	   MATERIAL	   MAT. COST	NATURAL	    REQUARED	 CONSUME   HARD REQ.   IMPORT	IMP. LIMIT	   EXPORT	EXP. LIMIT	   DISPLAY
	{	t_HUMAN_TRANSPORT_CENTER,	0,		{SHIPS,			NOT_SET,	HUM_TRANS_CENT_SHIPS_LIM_0,	 true,		GROUP_FROM_4,		POPULATION,			1,		  1400,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_TRANSPORT_CENTER,	1,		{SHIPS,			NOT_SET,	HUM_TRANS_CENT_SHIPS_LIM_1,	 true,		GROUP_FROM_4,		POPULATION,			1,		  1400,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_TRANSPORT_CENTER,	2,		{SHIPS,			NOT_SET,	HUM_TRANS_CENT_SHIPS_LIM_2,	 true,		GROUP_FROM_4,		POPULATION,			1,		  1400,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},
	{	t_HUMAN_TRANSPORT_CENTER,	3,		{SHIPS,			NOT_SET,	HUM_TRANS_CENT_SHIPS_LIM_3,	 true,		GROUP_FROM_4,		POPULATION,			1,		  1400,			NOT_SET,		FERTILITY,	MAT_COST_1,	true,		NO_RES,		 NOT_SET,	NOT_SET,	true,	PERCENT_25,		false,	NOT_SET,		true}},

};

static DefResSetting s_humanDefResValue[]
{
	//	BUILDING TYPE			RES TYPE			DEF VALUE
	{	t_HUMAN_SETTLERS,		POPULATION,			NOT_SET					},
	{	t_HUMAN_SETTLERS,		SUPPLY,				NOT_SET					},
	{	t_HUMAN_SETTLERS,		INFROSTRUCTURE,		HUM_SETTL_INF_LVL_1 + 1	},

	//	BUILDING TYPE				RES TYPE			DEF VALUE
	{	t_HUMAN_COLONY_CENTER,		POPULATION,			NOT_SET						},
	{	t_HUMAN_COLONY_CENTER,		SUPPLY,				NOT_SET						},
	{	t_HUMAN_COLONY_CENTER,		INFROSTRUCTURE,		HUM_COL_CENT_INF_LVL_1 + 1	},
	{	t_HUMAN_COLONY_CENTER,		SHIPS,				1							},

	//	BUILDING TYPE					RES TYPE			DEF VALUE
	{	t_HUMAN_TRANSPORT_CENTER,		POPULATION,			NOT_SET						},
	{	t_HUMAN_TRANSPORT_CENTER,		SUPPLY,				NOT_SET						},
	{	t_HUMAN_TRANSPORT_CENTER,		INFROSTRUCTURE,		HUM_TRANS_CENT_INF_LVL_1 + 1},
	{	t_HUMAN_TRANSPORT_CENTER,		SHIPS,				1							},
};



HumanPlayer::HumanPlayer(int ID):
	Player(ID, Human)
{
	m_builManager = new HumanBuildManager();
	m_unitFactory = new HumanUnitFactory(m_ID);
	m_buildingFactory = new HumanBuildingFactory(m_ID);
	m_abilityManager = new HumanAbilityManager(m_ID);
}

HumanPlayer::~HumanPlayer()
{
	if(m_builManager != nullptr)
	{
		delete m_builManager;
	}

	if(m_abilityManager != nullptr)
	{
		delete m_abilityManager;
	}

	if(m_unitFactory != nullptr)
	{
		delete m_unitFactory;
	}

	if(m_buildingFactory != nullptr)
	{
		delete m_buildingFactory;
	}
}

void HumanPlayer::init()
{
	Player::init();


	//setup res prototupe
	setupHumanResPrototypes();

	//setup default values for resourses
	setupDefaltValues();

	//setup factory to UnitController
	UnitController::getInstance()->addUnitFactory(m_unitFactory, m_ID);
	ObjectController::getInstance()->addBuildingFactory(m_buildingFactory, m_ID);

	// init it here by the reason what HumanAbilityManager have dependency on UnitFactory
	m_abilityManager->init();
}


void HumanPlayer::setupHumanResPrototypes()
{
	int prototypeStorageSize = sizeof(s_humanResourses) / sizeof(ResPrototypeStotage);

	for(int i = 0; i < prototypeStorageSize; i++)
	{
		ResPrototypeStotage& proto = s_humanResourses[i];

		OBJECT_TYPE buildType = proto.type;
		int lvl = proto.level;
		Resourse* res = &(proto.resorse);

		setResToPrototype(buildType, res, lvl);
	}

}

void HumanPlayer::setupDefaltValues()
{
	int defValStorageSize = sizeof(s_humanDefResValue) / sizeof(DefResSetting);

	for(int i = 0; i < defValStorageSize; i++)
	{
		DefResSetting& proto = s_humanDefResValue[i];

		OBJECT_TYPE buildType = proto.type;
		RESOURSES resType = proto.resType;
		int value = proto.defaulValue;

		setDefValue(buildType, resType, value);
	}
}
